# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'corry.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 563)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: white;\n"
"}")
        self.countryFlag = QtWidgets.QLabel(Dialog)
        self.countryFlag.setGeometry(QtCore.QRect(20, 10, 250, 167))
        self.countryFlag.setStyleSheet("#countryFlag {\n"
"    border-radius: 20px;\n"
"    color:red;\n"
"}")
        self.countryFlag.setText("")
        self.countryFlag.setPixmap(QtGui.QPixmap("images/custom – 1.jpg"))
        self.countryFlag.setObjectName("countryFlag")
        self.bg = QtWidgets.QFrame(Dialog)
        self.bg.setGeometry(QtCore.QRect(20, 200, 511, 331))
        self.bg.setStyleSheet("#bg {\n"
"    background-color: rgb(71,63,151);\n"
"border-radius: 20px\n"
"        \n"
"}")
        self.bg.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bg.setObjectName("bg")
        self.frame_recovered = QtWidgets.QFrame(self.bg)
        self.frame_recovered.setGeometry(QtCore.QRect(20, 170, 151, 141))
        self.frame_recovered.setStyleSheet("#frame_recovered {\n"
"background-color: rgb(76, 217, 123);\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.frame_recovered.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_recovered.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_recovered.setObjectName("frame_recovered")
        self.recovered = QtWidgets.QLabel(self.frame_recovered)
        self.recovered.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.recovered.setFont(font)
        self.recovered.setStyleSheet("color: rgb(255, 255, 255);")
        self.recovered.setObjectName("recovered")
        self.recoveredCount = QtWidgets.QLabel(self.frame_recovered)
        self.recoveredCount.setGeometry(QtCore.QRect(10, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.recoveredCount.setFont(font)
        self.recoveredCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.recoveredCount.setStyleSheet("color: rgb(255, 255, 255);")
        self.recoveredCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.recoveredCount.setObjectName("recoveredCount")
        self.frame_affected = QtWidgets.QFrame(self.bg)
        self.frame_affected.setGeometry(QtCore.QRect(20, 20, 231, 141))
        self.frame_affected.setStyleSheet("#frame_affected {\n"
"    background-color: #FFB259;\n"
"    border-radius: 20px;\n"
"}")
        self.frame_affected.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_affected.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_affected.setObjectName("frame_affected")
        self.confirmed = QtWidgets.QLabel(self.frame_affected)
        self.confirmed.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.confirmed.setFont(font)
        self.confirmed.setStyleSheet("color: rgb(255, 255, 255);")
        self.confirmed.setObjectName("confirmed")
        self.confirmedCount = QtWidgets.QLabel(self.frame_affected)
        self.confirmedCount.setGeometry(QtCore.QRect(20, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.confirmedCount.setFont(font)
        self.confirmedCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.confirmedCount.setStyleSheet("color: rgb(255, 255, 255);")
        self.confirmedCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.confirmedCount.setObjectName("confirmedCount")
        self.frame_deaths = QtWidgets.QFrame(self.bg)
        self.frame_deaths.setGeometry(QtCore.QRect(260, 20, 231, 141))
        self.frame_deaths.setStyleSheet("background-color: rgb(255, 89, 89);\n"
"    border-radius: 20px;")
        self.frame_deaths.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_deaths.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_deaths.setObjectName("frame_deaths")
        self.deaths = QtWidgets.QLabel(self.frame_deaths)
        self.deaths.setGeometry(QtCore.QRect(20, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.deaths.setFont(font)
        self.deaths.setStyleSheet("color: rgb(255, 255, 255);")
        self.deaths.setObjectName("deaths")
        self.deathsCount = QtWidgets.QLabel(self.frame_deaths)
        self.deathsCount.setGeometry(QtCore.QRect(20, 80, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.deathsCount.setFont(font)
        self.deathsCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.deathsCount.setStyleSheet("color: rgb(255, 255, 255);")
        self.deathsCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.deathsCount.setObjectName("deathsCount")
        self.frame_active = QtWidgets.QFrame(self.bg)
        self.frame_active.setGeometry(QtCore.QRect(180, 170, 151, 141))
        self.frame_active.setStyleSheet("\n"
"background-color: rgb(76, 181, 255);\n"
"    border-radius: 20px;")
        self.frame_active.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_active.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_active.setObjectName("frame_active")
        self.active = QtWidgets.QLabel(self.frame_active)
        self.active.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.active.setFont(font)
        self.active.setStyleSheet("color: rgb(255, 255, 255);")
        self.active.setObjectName("active")
        self.activeCount = QtWidgets.QLabel(self.frame_active)
        self.activeCount.setGeometry(QtCore.QRect(10, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.activeCount.setFont(font)
        self.activeCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.activeCount.setStyleSheet("color: rgb(255, 255, 255);")
        self.activeCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.activeCount.setObjectName("activeCount")
        self.frame_critical = QtWidgets.QFrame(self.bg)
        self.frame_critical.setGeometry(QtCore.QRect(340, 170, 151, 141))
        self.frame_critical.setStyleSheet("background-color: rgb(144, 89, 255);\n"
"    border-radius: 20px;")
        self.frame_critical.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_critical.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_critical.setObjectName("frame_critical")
        self.critical = QtWidgets.QLabel(self.frame_critical)
        self.critical.setGeometry(QtCore.QRect(20, 10, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.critical.setFont(font)
        self.critical.setStyleSheet("color: rgb(255, 255, 255);")
        self.critical.setObjectName("critical")
        self.criticalCount = QtWidgets.QLabel(self.frame_critical)
        self.criticalCount.setGeometry(QtCore.QRect(10, 90, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.criticalCount.setFont(font)
        self.criticalCount.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.criticalCount.setStyleSheet("color: rgb(255, 255, 255);")
        self.criticalCount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.criticalCount.setObjectName("criticalCount")
        self.coronavirus = QtWidgets.QLabel(Dialog)
        self.coronavirus.setGeometry(QtCore.QRect(350, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(20)
        font.setItalic(True)
        self.coronavirus.setFont(font)
        self.coronavirus.setStyleSheet("color: rgb(143, 143, 143);")
        self.coronavirus.setObjectName("coronavirus")
        self.covid19 = QtWidgets.QLabel(Dialog)
        self.covid19.setGeometry(QtCore.QRect(350, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(26)
        font.setItalic(True)
        self.covid19.setFont(font)
        self.covid19.setStyleSheet("color: rgb(206, 0, 0);")
        self.covid19.setObjectName("covid19")
        self.country = QtWidgets.QLineEdit(Dialog)
        self.country.setGeometry(QtCore.QRect(300, 109, 221, 31))
        self.country.setStyleSheet("border-color: rgb(143, 143, 143);")
        self.country.setObjectName("country")
        self.selectCountry = QtWidgets.QLabel(Dialog)
        self.selectCountry.setGeometry(QtCore.QRect(300, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(11)
        font.setItalic(True)
        self.selectCountry.setFont(font)
        self.selectCountry.setStyleSheet("color: rgb(143, 143, 143);")
        self.selectCountry.setObjectName("selectCountry")
        self.logo = QtWidgets.QLabel(Dialog)
        self.logo.setGeometry(QtCore.QRect(340, 530, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(9)
        font.setItalic(False)
        self.logo.setFont(font)
        self.logo.setStyleSheet("color: rgb(143, 143, 143);")
        self.logo.setObjectName("logo")
        self.lastUpdated = QtWidgets.QLabel(Dialog)
        self.lastUpdated.setGeometry(QtCore.QRect(300, 140, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat Medium")
        font.setPointSize(8)
        font.setItalic(False)
        font.setKerning(True)
        self.lastUpdated.setFont(font)
        self.lastUpdated.setStyleSheet("color: rgb(143, 143, 143);")
        self.lastUpdated.setObjectName("lastUpdated")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.recovered.setText(_translate("Dialog", "Recovered"))
        self.recoveredCount.setText(_translate("Dialog", "0"))
        self.confirmed.setText(_translate("Dialog", "Confirmed"))
        self.confirmedCount.setText(_translate("Dialog", "0"))
        self.deaths.setText(_translate("Dialog", "Deaths"))
        self.deathsCount.setText(_translate("Dialog", "0"))
        self.active.setText(_translate("Dialog", "Active"))
        self.activeCount.setText(_translate("Dialog", "0"))
        self.critical.setText(_translate("Dialog", "Critical"))
        self.criticalCount.setText(_translate("Dialog", "0"))
        self.coronavirus.setText(_translate("Dialog", "Coronavirus"))
        self.covid19.setText(_translate("Dialog", "COVID-19"))
        self.selectCountry.setText(_translate("Dialog", "Search Country"))
        self.logo.setText(_translate("Dialog", "Designed by: Prince Radebe"))
        self.lastUpdated.setText(_translate("Dialog", "last updated: 01-May-2020"))
